version: '3.4'

services:
  groupdb:
    container_name: groupdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  activityme.identityserver:
    container_name: activityme.identityserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "5001:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  activityme.groups.api:
    container_name: group.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ServiceSettings:ServiceName=Groups"
      - "MongoDbSettings:Host=groupdb"
      - "MongoDbSettings:Port=27017"
    depends_on:
      - groupdb
      - activityme.identityserver
    ports:
      - "8000:80"

