version: '3.4'

services:
  groupdb:
    image: mongo

  activityme.groups.api:
    image: ${DOCKER_REGISTRY-}activitymegroupsapi
    build:
      context: .
      dockerfile: ActivityMe.Groups.API/Dockerfile
    volumes:
      - ~/.vsdbg:/remote_debugger:rw

volumes:
  mongo_data: 
  
  